{
 "title": "IoT",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Membrane Switch",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"events\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"key_pressed\")"
    }
   ]
  },
  {
   "title": "Door sensor",
   "type": "table",
   "description": "Table visualization (no numeric values) of button press",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"events\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"button_press\")"
    }
   ]
  },
  {
   "title": "PIR",
   "type": "table",
   "description": "Table visualization (no numeric values) of move detection",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"events\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pir_move\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"event\")"
    }
   ]
  },
  {
   "title": "UDS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"measurements\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Distance\")\r\n  |> group(columns: [\"name\"])"
    }
   ]
  },
  {
   "title": "DHT - Temperature",
   "type": "timeseries",
   "description": "Visualizing dht temperature",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"measurements\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"measurement\")\r\n"
    }
   ]
  },
  {
   "title": "DHT - Humidity",
   "type": "timeseries",
   "description": "Visualizing dht humidity",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"measurements\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Humidity\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"measurement\")\r\n"
    }
   ]
  },
  {
   "title": "Door Light",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "query": "from(bucket: \"events\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"door_light_toggled\")"
    }
   ]
  },
  {
   "title": "Door buzzer",
   "type": "table",
   "description": "Table visualization (no numeric values) of buzzer sound",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "query": "from(bucket: \"events\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"buzzer_sound\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"event\")"
    }
   ]
  }
 ]
}