version: "3.7"
services:

  # mqtt5 eclipse-mosquitto
  mqtt5:
    image: eclipse-mosquitto
    container_name: mqtt5_iot
    ports:
      - 1883:1883 #default mqtt port
      - 9001:9001 #default mqtt port for websockets
    volumes:
      - ./broker-config:/mosquitto/config:rw
      - ./broker-data:/mosquitto/data:rw
      - ./broker-log:/mosquitto/log:rw
    networks:
      - iot-network
    env_file:
      - .env

  influxdb:
    image: influxdb
    container_name: influxdb_iot
    ports:
      - 8086:8086 # InfluxDB API port
    volumes:
      - ./influxdb/data:/var/lib/influxdb2:rw
    networks:
      - iot-network
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]

volumes:
  config:
  data:
  log:
  influxdb:

networks:
  iot-network:
    name: iot-network
