#!/bin/bash

# Protects script from continuing with an error
set -eu -o pipefail

# Ensures environment variables are set
export DOCKER_INFLUXDB_INIT_MODE=$INFLUXDB_INIT_MODE
export DOCKER_INFLUXDB_INIT_USERNAME=$INFLUXDB_ADMIN_USER
export DOCKER_INFLUXDB_INIT_PASSWORD=$INFLUXDB_ADMIN_PASSWORD
export DOCKER_INFLUXDB_INIT_ORG=$INFLUXDB_ORGANIZATION
export DOCKER_INFLUXDB_INIT_BUCKET=$INFLUXDB_BUCKET
export DOCKER_INFLUXDB_INIT_RETENTION=$INFLUXDB_INIT_RETENTION
export DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=$INFLUXDB_TOKEN
export DOCKER_INFLUXDB_INIT_PORT=$INFLUXDB_INIT_PORT
export DOCKER_INFLUXDB_INIT_HOST=$INFLUXDB_INIT_HOST

# Conducts initial InfluxDB using the CLI
influx setup --skip-verify --bucket ${DOCKER_INFLUXDB_INIT_BUCKET} --retention ${DOCKER_INFLUXDB_INIT_RETENTION} --token ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN} --org ${DOCKER_INFLUXDB_INIT_ORG} --username ${DOCKER_INFLUXDB_INIT_USERNAME} --password ${DOCKER_INFLUXDB_INIT_PASSWORD} --host http://${DOCKER_INFLUXDB_INIT_HOST}:8086 --force
